---
- hosts: jumpbox
  become: yes 
  tasks:
  - name: stop and disable docker service
    service:
      name: docker
      state: stopped
      enabled: no
  - name: remove docker
    yum:
      name: docker
      state: absent
  - name: stop and disable nginx service
    service:
      name: nginx
      state: stopped
      enabled: no
  - name: remove nginx
    yum:
      name: nginx
      state: absent

